
;
; Data used to generate directory in CBM BASIC format
;

dir_hdr:                     ; 32 bytes - header

	!byte $01, $08           ; program location
	!byte $01, $01           ; link to the next line - dummy, will be regenerated by BASIC
	!byte $00, $00           ; line number 0
	!byte $12, $22           ; reverse mode, quote
	!pet "                "  ; space for disk/directory name
    !byte $22, $20           ; quote, space
	!pet "00 2a"             ; default ID, disk format
	!byte $00                ; end of the line

dir_hdr_sd:                  ; 32 bytes - header

	!byte $01, $08           ; program location
	!byte $01, $01           ; link to the next line - dummy, will be regenerated by BASIC
	!byte $00, $00           ; line number 0
	!byte $12, $22           ; reverse mode, quote
	!pet "sd card         "  ; space for disk/directory name
    !byte $22, $20           ; quote, space
	!pet "fat32"             ; filesystem
	!byte $00                ; end of the line

dir_end:                     ; 19 bytes

	!byte $01, $01           ; link to the next line - dummy, will be regenerated by BASIC
	!byte $00, $00           ; line number 0
	!pet "blocks free."
	!byte $00, $00, $00      ; end of the line, end of program marker
